// Generated by scripts/extract-hyperheart-assets.mjs. HyperHeart images: CC BY-NC 4.0.
// Attribution and source relationships: third_party/hyperheart/NOTICE.md and asset-manifest.json.
import type { HyperHeartAssetSet, HyperHeartPhaseId } from './types';
import heart0 from '../../../assets/tools/hyperheart/heart/atrial-systole.png';
import wiggers0 from '../../../assets/tools/hyperheart/wiggers/atrial-systole.png';
import ecg0 from '../../../assets/tools/hyperheart/ecg/atrial-systole.png';
import sounds0 from '../../../assets/tools/hyperheart/sounds/atrial-systole.png';
import heart1 from '../../../assets/tools/hyperheart/heart/isovolumetric-contraction.png';
import wiggers1 from '../../../assets/tools/hyperheart/wiggers/isovolumetric-contraction.png';
import ecg1 from '../../../assets/tools/hyperheart/ecg/isovolumetric-contraction.png';
import sounds1 from '../../../assets/tools/hyperheart/sounds/isovolumetric-contraction.png';
import heart2 from '../../../assets/tools/hyperheart/heart/rapid-ejection.png';
import wiggers2 from '../../../assets/tools/hyperheart/wiggers/rapid-ejection.png';
import ecg2 from '../../../assets/tools/hyperheart/ecg/rapid-ejection.png';
import sounds2 from '../../../assets/tools/hyperheart/sounds/rapid-ejection.png';
import heart3 from '../../../assets/tools/hyperheart/heart/reduced-ejection.png';
import wiggers3 from '../../../assets/tools/hyperheart/wiggers/reduced-ejection.png';
import ecg3 from '../../../assets/tools/hyperheart/ecg/reduced-ejection.png';
import sounds3 from '../../../assets/tools/hyperheart/sounds/reduced-ejection.png';
import heart4 from '../../../assets/tools/hyperheart/heart/isovolumetric-relaxation.png';
import wiggers4 from '../../../assets/tools/hyperheart/wiggers/isovolumetric-relaxation.png';
import ecg4 from '../../../assets/tools/hyperheart/ecg/isovolumetric-relaxation.png';
import sounds4 from '../../../assets/tools/hyperheart/sounds/isovolumetric-relaxation.png';
import heart5 from '../../../assets/tools/hyperheart/heart/rapid-ventricular-filling.png';
import wiggers5 from '../../../assets/tools/hyperheart/wiggers/rapid-ventricular-filling.png';
import ecg5 from '../../../assets/tools/hyperheart/ecg/rapid-ventricular-filling.png';
import sounds5 from '../../../assets/tools/hyperheart/sounds/rapid-ventricular-filling.png';
import heart6 from '../../../assets/tools/hyperheart/heart/reduced-ventricular-filling.png';
import wiggers6 from '../../../assets/tools/hyperheart/wiggers/reduced-ventricular-filling.png';
import ecg6 from '../../../assets/tools/hyperheart/ecg/reduced-ventricular-filling.png';
import sounds6 from '../../../assets/tools/hyperheart/sounds/reduced-ventricular-filling.png';

export const hyperHeartAssets = {
  'atrial-systole': { heart: heart0, wiggers: wiggers0, ecg: ecg0, sounds: sounds0 },
  'isovolumetric-contraction': { heart: heart1, wiggers: wiggers1, ecg: ecg1, sounds: sounds1 },
  'rapid-ejection': { heart: heart2, wiggers: wiggers2, ecg: ecg2, sounds: sounds2 },
  'reduced-ejection': { heart: heart3, wiggers: wiggers3, ecg: ecg3, sounds: sounds3 },
  'isovolumetric-relaxation': { heart: heart4, wiggers: wiggers4, ecg: ecg4, sounds: sounds4 },
  'rapid-ventricular-filling': { heart: heart5, wiggers: wiggers5, ecg: ecg5, sounds: sounds5 },
  'reduced-ventricular-filling': { heart: heart6, wiggers: wiggers6, ecg: ecg6, sounds: sounds6 },
} as const satisfies Record<HyperHeartPhaseId, HyperHeartAssetSet>;
